#!/bin/bash

if ! [ -x "$(command -v pylint)" ]; then
  echo 'Error: pylint is not installed.' >&2
  exit 1
fi

# Получение списка всех Python-файлов, подготовленных для коммита
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')

# Если нет Python-файлов, выход
if [ -z "$files" ]; then
  exit 0
fi

# Запуск pylint для всех подготовленных Python-файлов
pylint $files
if [ $? -ne 0 ]; then
  echo "Pylint found issues. Commit aborted."
  exit 1
fi
